### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

vector = np.random.rand(10)

matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

print("Вектор:")
print(vector)
print("Розмір вектора:", vector.shape)

print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)

Вектор:
[0.32848599 0.89685386 0.63857184 0.56823246 0.15414182 0.28474499
 0.67801418 0.75017678 0.37489518 0.52784228]
Розмір вектора: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector_plus_10 = np.round(vector + 10, 2)

matrix_times_2 = matrix * 2

vector_squared = vector**2

print("Вектор + 10, округлений до 2 знаків:")
print(vector_plus_10)

print("\nМатриця, помножена на 2:")
print(matrix_times_2)

print("\nКвадрати елементів вектора:")
print(vector_squared)

Вектор + 10, округлений до 2 знаків:
[10.33 10.9  10.64 10.57 10.15 10.28 10.68 10.75 10.37 10.53]

Матриця, помножена на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

Квадрати елементів вектора:
[0.10790305 0.80434685 0.40777399 0.32288813 0.0237597  0.08107971
 0.45970323 0.56276519 0.14054639 0.27861747]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
result_matrix = np.dot(B, A)

print("result_matrix:")
print(result_matrix)
print("Форма result_matrix:", result_matrix.shape)

result_vector = np.dot(result_matrix, C)
print("\nМноження result_matrix та C:")
print(result_vector)
print("Форма:", result_vector.shape)

result_matrix_D = np.dot(result_matrix, D)
print("\nМноження result_matrix та D:")
print(result_matrix_D)
print("Форма:", result_matrix_D.shape)

result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]
Форма result_matrix: (2, 2)

Множення result_matrix та C:
[[0.5202]
 [0.2846]]
Форма: (2, 1)

Множення result_matrix та D:
[[0.5202 0.7281]
 [0.2846 0.2034]]
Форма: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [25]:
T_matrix = result_matrix.T
print("Транспонована матриця result_matrix:")
print(T_matrix)

Транспонована матриця result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [28]:
T_vector = vector.T
print("\nТранспонований вектор vector:")
print(T_vector)
print("Форма:", T_vector.shape)


Транспонований вектор vector:
[0.32848599 0.89685386 0.63857184 0.56823246 0.15414182 0.28474499
 0.67801418 0.75017678 0.37489518 0.52784228]
Форма: (10,)


Немає змін, бо вектор це 1Д масив і транспонування не працює на ньому так, як на матрицях.

In [29]:
column_vector = np.expand_dims(vector, axis=1)
print("\ncolumn_vector (vector з доданою віссю axis=1):")
print(column_vector)
print("Форма:", column_vector.shape)


column_vector (vector з доданою віссю axis=1):
[[0.32848599]
 [0.89685386]
 [0.63857184]
 [0.56823246]
 [0.15414182]
 [0.28474499]
 [0.67801418]
 [0.75017678]
 [0.37489518]
 [0.52784228]]
Форма: (10, 1)


Тепер це став вертикальний вектор, тобто колонка, а не рядочок.

In [33]:
T_column_vector = column_vector.T
print("\nТранспонований column_vector:")
print(T_column_vector)
print("Форма:", T_column_vector.shape)


Транспонований column_vector:
[[0.32848599 0.89685386 0.63857184 0.56823246 0.15414182 0.28474499
  0.67801418 0.75017678 0.37489518 0.52784228]]
Форма: (1, 10)


In [ ]:
Тепер вектор став 